import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <style jsx>
      {`
      h2{
        font-size:30px;
      }
      h3{
        font-size:20px;
      }
      `}
    </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, huntingcoder blog, huntingcoder" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     

      <main className={`${styles.main} ${inter.className}`}>
       
          <h1 className="mySpan dummy">Hunting coder</h1>
          <div className={styles.imagewrap}>
          <Image className={styles.myimg} src="/coder.jpg" width={210} height={120}/>
          </div>
        <div className="blogs">
          <p>A blog for hunting coders by a hunting coder</p><br/>
         
          <h2>Latest blogs</h2>
         
          <div className={styles.blogpost}>
           <h3>how to learn javascript?</h3>
           <p>javascript is the language used to design logic for the web </p> 
          </div>
  
          <div className={styles.blogpost}>
           <h3>how to learn javascript?</h3>
           <p>javascript is the language used to design logic for the web </p> 
          </div>
          
          <div className={styles.blogpost}>
           <h3>how to learn javascript?</h3>
           <p>javascript is the language used to design logic for the web </p> 
          </div>
        
        </div>
      </main>
    </>
    )
  }